module Contexts
  module Criminals
    def create_criminals
      @joker    = FactoryBot.create(:criminal)
      @catwoman = FactoryBot.create(:criminal, first_name: "Selina", last_name: "Kyle", aka: "Catwoman", convicted_felon: true)
      @bane     = FactoryBot.create(:criminal, first_name: "Edmund", last_name: "Dorrance", aka: "Bane", convicted_felon: true, enhanced_powers: true)
      @maroni   = FactoryBot.create(:criminal, first_name: "Salvatore", last_name: "Maroni", aka: nil)
    end
    
    def destroy_criminals
      @joker.delete
      @catwoman.delete
      @bane.delete
      @maroni.delete
    end

    def create_rogues_gallery
      @joker       = FactoryBot.create(:criminal, notes: "The Joker is a homicidal maniac with a clown-like appearance, bent on creating havoc in Gotham City and fighting a never-ending battle against Batman. His arsenal of weapons includes razor-cards, acid-spewing flowers, and fatal laughing-gas. He is responsible for countless deaths but has also been certified as insane for legal proceedings.")
      @catwoman    = FactoryBot.create(:criminal, first_name: "Selina", last_name: "Kyle", aka: "Catwoman", convicted_felon: true, notes: "Selina Kyle is an accomplished jewel thief. Highly acrobatic and able to move quickly and silently.  Catwoman is adept at using many weapons, but her favorite weapon is a whip.  In normal life, Selina Kyle has been in an on-again-off-again relationship with billionaire Bruce Wayne.")
      @bane        = FactoryBot.create(:criminal, first_name: "Edmund", last_name: "Dorrance", aka: "Bane", convicted_felon: true, enhanced_powers: true, notes: "The international masked criminal known as Bane has immense strength that comes from a super-steroid called Venom. Bane's raw power coupled with his genius level intellect makes him a considerable threat to Batman, having once succeeded in breaking Batman's back.")
      @hush        = FactoryBot.create(:criminal, first_name: "Thomas", last_name: "Elliot", aka: "Hush", convicted_felon: true, notes: "Being a victim of abuse rendered Thomas Elliot sociopathic. Before even his teenage years, he was already operating on a high level of sociopathy, going so far as severing the brake line of his parents' car to gain independence from them and inherit the Elliot family fortune. Dr. Thomas Wayne operated on and saved his mother, foiling the young Elliot's plan of parricide. One of the finest surgeons in Gotham City, Thomas Elliot has an incredible, genius-level intellect and is also a master planner, with tactical skills rivaling those of the Caped Crusader. Hush's greatest asset is his talent for thinking like his opponents and for using their abilities against them. Hush is also an expert marksman.")
      @killer_croc = FactoryBot.create(:criminal, first_name: "Waylon", last_name: "Jones", aka: "Killer Croc", convicted_felon: true, enhanced_powers: true, notes: "Waylon Jones has a medical condition that warped his body into a massive crocodile-like form. As Croc descended into madness, he sharpened his teeth to razor points and began murdering innocent victims. He possesses super-strength and is immune to toxins.")
      @harley      = FactoryBot.create(:criminal, first_name: "Harleen", last_name: "Quinzel", aka: "Harley Quinn", convicted_felon: true, notes: "Dr. Harleen Quinzel was the Joker's psychiatrist at Arkham Asylum until she fell in love with him and subsequently reinvented herself as his madcap sidekick, Harley Quinn. She is often mistreated by the Joker, but that rarely changes how she feels about him.")
      @deathstroke = FactoryBot.create(:criminal, first_name: "Slade", last_name: "Wilson", aka: "Deathstroke", convicted_felon: true, enhanced_powers: true, notes: "Chosen for a secret experiment, the Army imbued him with enhanced physical powers in an attempt to create metahuman super soldiers for the U.S. military. Deathstroke became a mercenary soon after the experiment when he defied orders. Slade Wilson's physical and mental attributes have been enhanced as a result of the experimental serum he was given; he possesses heightened strength, agility, durability, and reflexes, and has the ability to utilize up to 90 percent of his brain capacity. Deathstroke also possesses a regenerative healing factor that enables him to recover from physical injury much more rapidly than a normal human; it does, however, have its limits, as it could not heal his missing eye nor can it regenerate entire limbs. This enhanced endurance enables him to survive otherwise fatal injuries, though recovering from such injuries renders him temporarily insane and ferociously animalistic. In addition to being a tactical genius with years of military experience, Deathstroke is an expert in many forms of unarmed combat and martial arts as well, serving as a master of Bōjutsu, Boxing, Jojutsu, Judo, Jujitsu, Karate, and Ninjutsu.")
      @clayface    = FactoryBot.create(:criminal, first_name: "Matt", last_name: "Hagan", aka: "Clayface", convicted_felon: true, enhanced_powers: true, notes: "Treasure-hunter Matt Hagen was transformed into the monstrous Clayface by a pool of radioactive protoplasm. He now possesses super-strength and can change his claylike body into any form.")
      @riddler     = FactoryBot.create(:criminal, first_name: "Edward", last_name: "Nigma", aka: "Riddler", convicted_felon: true, notes: "Edward Nigma is a criminal mastermind who has a compulsion to challenge Batman by leaving clues to his crimes in the form of riddles, puzzles, and word-games. Nigma's intelligence rivals that of Batman. Nigma often carries a question-mark cane around with him, as well as many other trick puzzle gimmicks.")
      @penguin     = FactoryBot.create(:criminal, first_name: "Oswald", last_name: "Cobblepot", aka: "Penguin", convicted_felon: true, notes: "Oswald Chesterfield Cobblepot is a devious bird-themed crime boss who is seldom seen without one of his trick umbrellas. The Penguin uses his nightclub, the Iceberg Lounge, as a front for his criminal activities.")
      @poison_ivy  = FactoryBot.create(:criminal, first_name: "Pamela", last_name: "Isley", aka: "Poison Ivy", convicted_felon: true, enhanced_powers: true, notes: "Pamela Lillian Isley, a former student of advanced botanical biochemistry, employs plants of all varieties and their derivatives in her crimes. She has the ability to control all plant life and can create new henchmen with her mutated seeds. She is immune to all plant-based poisons.")
      @mr_freeze   = FactoryBot.create(:criminal, first_name: "Victor", last_name: "Fries", aka: "Mr. Freeze", convicted_felon: true, notes: "Dr. Victor Fries is a scientist who accidentally spilled cryogenic chemicals on himself while inventing a freeze-gun. Now requiring subzero temperatures to survive, he uses freeze-inducing weaponry and must wear a fully contained, refrigerated ice-suit. Fries was later reinvented as a tragic figure and occasional antihero: Victor Fries was a brilliant cryogenicist whose beloved wife Nora fell terminally ill. He obsessively searched for a way to cure her, until an industrial accident caused by a greedy business executive turned Fries into a mutant who can only survive in subzero temperatures.")
      @ras_al_ghul = FactoryBot.create(:criminal, first_name: "Ra's", last_name: "al Ghul", aka: nil, convicted_felon: false, enhanced_powers: true, notes: "Ra's al Ghul is a centuries-old international eco-terrorist who believes that his actions help bring balance to the world. Ra's al Ghul is the founder of the League of Assassins. Ra's' greatest tools are his Lazarus Pits, which heal any injury including recent death and restore the user back to the prime of life, but cause temporary insanity. His constant exposure to the pits have granted him slightly enhanced endurance, strength, and healing but also comes with the price of a gradual onset of insanity if overused. Due to his expanded life span, Ra's has accumulated a vast knowledge of hand-to-hand combat, chemistry, detective artistry, physics, and martial arts. He has also gained many international contacts and a vast fortune over the course of centuries.")
      @scarecrow   = FactoryBot.create(:criminal, first_name: "Jonathan", last_name: "Crane", aka: "Scarecrow", convicted_felon: true, enhanced_powers: true, notes: "Professor Jonathan Crane was an outcast in childhood due to the constant bullying, until he grew up to face his fears as a psychologist and biochemist in the specialization of fear. Kicked out of a university for his unorthodox teaching methods, he now dresses symbolically as a scarecrow, and employs a toxin that causes its victims to hallucinate the presence of what they most fear.")
      @two_face    = FactoryBot.create(:criminal, first_name: "Harvey", last_name: "Dent", aka: "Two Face", convicted_felon: true, notes: "Harvey Dent was a district attorney until half of his face was disfigured after being assaulted by mob boss Sal Maroni. Having developed Dissociative identity disorder, Harvey Dent is obsessed with duality and must make most of his decisions with the flip of a coin. As Two-Face, Harvey Dent commits crimes themed around the number two.")
      @man_bat     = FactoryBot.create(:criminal, first_name: "Kirk", last_name: "Langstrom", aka: "Man-Bat", convicted_felon: false, enhanced_powers: true, notes: "Dr. Kirk Langstrom invented a serum to give him echolocation to cure his growing deafness. The serum had an unforeseen side-effect, transforming him into the monstrous Man-Bat.")
      # puts "Created Rogues Gallery"
      # Other mobsters
      @maroni   = FactoryBot.create(:criminal, first_name: "Salvatore", last_name: "Maroni", aka: nil, convicted_felon: true, notes: "Sal Maroni is the leader of the Maroni Crime Family and the gangster most notable for scarring Harvey Dent.")
      @rfalcone   = FactoryBot.create(:criminal, first_name: "Carmine", last_name: "Falcone", aka: "The Roman", notes: "Carmine Falcone is a powerful crime boss and the leader of the Falcone Crime Family. He is the father of Alberto Falcone, Mario Falcone, and Sofia Falcone Gigante.")
      @sfalcone   = FactoryBot.create(:criminal, first_name: "Sophia", last_name: "Gigante", aka: nil, notes: "Sofia Falcone Gigante is the daughter of mob boss Carmine Falcone.")  
      puts "Building ..."
      @criminals = Criminal.alphabetical.to_a
    end
  end
end